import type { FrontendStateData } from '../types/telemetry';
import type { SystemEvent } from '../types/event';
import type { Track } from '../types/track';

export const getMockEvents = (): SystemEvent[] => [
  {
    id: 'evt-001',
    timestamp: new Date(Date.now() - 300000).toISOString(),
    severity: 'INFO',
    message: 'Simulated ground control station initialized.',
    source: 'SYSTEM',
  },
  {
    id: 'evt-002',
    timestamp: new Date(Date.now() - 240000).toISOString(),
    severity: 'INFO',
    message: 'Establish WebSocket link to simulator backend.',
    source: 'NETWORK',
  },
  {
    id: 'evt-003',
    timestamp: new Date(Date.now() - 180000).toISOString(),
    severity: 'WARNING',
    message: 'Video feed bandwidth degraded: Bitrate dropped below 1500 kbps.',
    source: 'VIDEO_STREAM',
  },
  {
    id: 'evt-004',
    timestamp: new Date(Date.now() - 120000).toISOString(),
    severity: 'INFO',
    message: 'Simulated vehicle status: ARMED and standing by for takeoff instruction.',
    source: 'VEHICLE',
  },
  {
    id: 'evt-005',
    timestamp: new Date(Date.now() - 60000).toISOString(),
    severity: 'CRITICAL',
    message: 'Simulated Launch Cell 3 reporting temperature spike (42°C).',
    source: 'LAUNCHBOX',
  },
];

export const getMockTracks = (): Track[] => [
  {
    track_id: 'TRK-001',
    name: 'Simulated UAV Alpha',
    latitude: 48.107 + 0.008,
    longitude: 11.613 + 0.005,
    altitude: 120.0,
    speed: 15.5,
    heading: 45.0,
    confidence: 0.95,
    status: 'TRACKING',
    last_update_timestamp: new Date().toISOString(),
    category: 'friendly',
  },
  {
    track_id: 'TRK-002',
    name: 'Simulated Target Bravo',
    latitude: 48.107 - 0.006,
    longitude: 11.613 - 0.008,
    altitude: 250.0,
    speed: 35.0,
    heading: 210.0,
    confidence: 0.88,
    status: 'TRACKING',
    last_update_timestamp: new Date().toISOString(),
    category: 'hostile',
  },
  {
    track_id: 'TRK-003',
    name: 'Simulated Cargo Liner',
    latitude: 48.107 + 0.012,
    longitude: 11.613 - 0.012,
    altitude: 450.0,
    speed: 80.0,
    heading: 90.0,
    confidence: 0.92,
    status: 'TRACKING',
    last_update_timestamp: new Date().toISOString(),
    category: 'neutral',
  },
  {
    track_id: 'TRK-004',
    name: 'Simulated Unknown Phantom',
    latitude: 48.107 - 0.002,
    longitude: 11.613 + 0.015,
    altitude: 80.0,
    speed: 8.0,
    heading: 315.0,
    confidence: 0.45,
    status: 'STALE',
    last_update_timestamp: new Date(Date.now() - 15000).toISOString(),
    category: 'unknown',
  },
];

export const getMockTelemetry = (): FrontendStateData => ({
  timestamp: new Date().toISOString(),
  tracks: getMockTracks(),
  vehicle: {
    id: 'VHC-SIM-01',
    latitude: 48.107,
    longitude: 11.613,
    altitude: 150.4,
    speed: 12.8,
    heading: 135,
    battery_percent: 88,
    gps_satellites: 14,
    connection_strength: 94,
    flight_mode: 'GUIDED',
    state: 'FLYING',
    last_updated: new Date().toISOString(),
  },
  launchbox: {
    status: 'READY',
    cells: [
      { cell_id: 1, status: 'LOADED', temperature: 24.5, payload_type: 'Simulated Flare' },
      { cell_id: 2, status: 'LOADED', temperature: 25.1, payload_type: 'Simulated Flare' },
      { cell_id: 3, status: 'ARMED', temperature: 42.0, payload_type: 'Simulated Probe' },
      { cell_id: 4, status: 'EMPTY', temperature: 22.8, payload_type: 'None' },
      { cell_id: 5, status: 'FIRED', temperature: 31.4, payload_type: 'Simulated Probe' },
      { cell_id: 6, status: 'EMPTY', temperature: 21.0, payload_type: 'None' },
    ],
    safety_switch: true, // safe
    key_inserted: true,
    last_updated: new Date().toISOString(),
  },
  video_health: {
    fps: 29.8,
    bitrate_kbps: 1450,
    latency_ms: 120,
    status: 'DEGRADED',
    last_updated: new Date().toISOString(),
  },
  diagnostics: {
    cpu_usage_percent: 18.4,
    memory_usage_mb: 245.2,
    disk_usage_percent: 44.1,
    network_rx_kbps: 185.3,
    network_tx_kbps: 24.8,
    uptime_seconds: 3600,
    packet_loss_percent: 0.1,
    last_updated: new Date().toISOString(),
  },
  events: getMockEvents(),
});
